# Generated by Django 4.2.8 on 2023-12-22 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitante',
            old_name='morador_resonsavel',
            new_name='morador_responsavel',
        ),
    ]
