# Generated by Django 4.2.8 on 2023-12-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_rename_morador_resonsavel_visitante_morador_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando autorização'), ('EM VISITANTE', 'Em visita'), ('FINALIZADO', 'Visita finalizada')], default='AGUARDANDO', max_length=12, verbose_name='Status'),
        ),
    ]
