# Generated by Django 4.2.8 on 2024-01-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0003_visitante_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='morador_responsavel',
            field=models.CharField(blank=True, max_length=194, verbose_name='Nome do associado responsável por autorizar a entrada do visitante '),
        ),
 
    ]
