# Generated by Django 4.2.8 on 2024-01-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0005_alter_visitante_options_visitante_dependente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='dependente',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='filiacao',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='tpsocio',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='validade',
        ),
        migrations.AlterField(
            model_name='visitante',
            name='morador_responsavel',
            field=models.CharField(blank=True, max_length=194, verbose_name='Nome do responsável por autorizar a entrada do visitante '),
        ),
    ]
