# Generated by Django 4.2.8 on 2024-01-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0006_remove_visitante_dependente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitante',
            options={'verbose_name': 'Visitante', 'verbose_name_plural': 'Visitantes'},
        ),
    ]
