# Generated by Django 4.2.8 on 2024-02-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0007_alter_visitante_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
    ]
