# Generated by Django 4.2.8 on 2024-01-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0003_socio_tpsocio_vinculado_dependente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socio',
            options={'verbose_name': 'Sócio', 'verbose_name_plural': 'Sócios'},
        ),
        migrations.AlterModelTable(
            name='socio',
            table='socio',
        ),
    ]
