# Generated by Django 4.2.8 on 2024-01-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0004_alter_socio_options_alter_socio_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('dependente', models.CharField(max_length=194, null=True, verbose_name='Dependente')),
                ('filiacao', models.CharField(choices=[('ESPOSA(o)', 'Esposa(o)'), ('FILHO(a)', 'Filho(a)'), ('NETO(a)', 'Neto(a)')], default='ESPOSA(o)', max_length=50, verbose_name='Filiacao')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='socio.socio')),
            ],
            options={
                'verbose_name': 'Dependente',
                'verbose_name_plural': 'Dependentes',
                'db_table': 'dependente',
            },
        ),
        migrations.DeleteModel(
            name='Vinculado',
        ),
    ]
