# Generated by Django 4.2.8 on 2024-01-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0005_dependentes_delete_vinculado'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dependentes',
            table='dependentes',
        ),
    ]
