# Generated by Django 4.2.8 on 2024-01-18 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0006_alter_dependentes_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependentes',
            name='dependente',
        ),
    ]
