# Generated by Django 4.2.8 on 2024-01-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0008_alter_dependentes_socio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
