# Generated by Django 4.2.8 on 2024-01-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0010_alter_dependentes_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentes',
            name='dtexame_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Validade do Exame'),
        ),
        migrations.AddField(
            model_name='dependentes',
            name='dtexame_ini',
            field=models.DateField(blank=True, null=True, verbose_name='Dia do Exame'),
        ),
        migrations.AddField(
            model_name='socio',
            name='dtexame_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Validade do Exame'),
        ),
        migrations.AddField(
            model_name='socio',
            name='dtexame_ini',
            field=models.DateField(blank=True, null=True, verbose_name='Dia do Exame'),
        ),
    ]
