# Generated by Django 4.2.8 on 2024-01-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0013_dependentes_foto_socio_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentes',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
