# Generated by Django 4.2.8 on 2024-02-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0016_dependentes_nrcart_socio_nrcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentes',
            name='registro',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='registro',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
