# Generated by Django 4.2.8 on 2024-02-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0021_remove_dependentes_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentes',
            name='ativo',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='Sim', max_length=10, verbose_name='Ativar Socio'),
        ),
        migrations.AddField(
            model_name='socio',
            name='ativo',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='Sim', max_length=10, verbose_name='Ativar Socio'),
        ),
        migrations.AlterField(
            model_name='dependentes',
            name='filiacao',
            field=models.CharField(choices=[('ESPOSA(o)', 'Esposa(o)'), ('FILHO(a)', 'Filho(a)'), ('NETO(a)', 'Neto(a)'), ('BISNETO(a)', 'Bisneto(a)'), ('SOGRO(a)', 'Sogro(a)'), ('PAIS', 'Pais')], default='ESPOSA(o)', max_length=50, verbose_name='Filiacao'),
        ),
    ]
