# Generated by Django 4.2.8 on 2024-02-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0023_socio_bairro_socio_cep_socio_cidade_socio_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentes',
            name='tpsocio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Socio'),
        ),
    ]
