# Generated by Django 4.2.8 on 2024-02-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0024_dependentes_tpsocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
    ]
