# Generated by Django 4.2.8 on 2024-03-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0025_alter_socio_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
