# Generated by Django 5.1.1 on 2024-10-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0027_alter_socio_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentes',
            name='dtexame_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da taxa da piscina'),
        ),
        migrations.AlterField(
            model_name='dependentes',
            name='dtexame_ini',
            field=models.DateField(blank=True, null=True, verbose_name='Data do pagamento da taxa da piscina'),
        ),
        migrations.AlterField(
            model_name='dependentes',
            name='filiacao',
            field=models.CharField(choices=[('ESPOSA(o)', 'Esposa(o)'), ('FILHO(a)', 'Filho(a)'), ('NETO(a)', 'Neto(a)'), ('BISNETO(a)', 'Bisneto(a)')], default='ESPOSA(o)', max_length=50, verbose_name='Filiacao'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='dtexame_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da taxa da piscina'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='dtexame_ini',
            field=models.DateField(blank=True, null=True, verbose_name='Data do pagamento da taxa da piscina'),
        ),
    ]
