# Generated by Django 4.2.8 on 2024-03-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0027_alter_socio_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentes',
            name='dtexame_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da taxa da piscina'),
        ),
        migrations.AlterField(
            model_name='dependentes',
            name='dtexame_ini',
            field=models.DateField(blank=True, null=True, verbose_name='Data do pagamento da taxa da piscina'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='dtexame_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da taxa da piscina'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='dtexame_ini',
            field=models.DateField(blank=True, null=True, verbose_name='Data do pagamento da taxa da piscina'),
        ),
    ]
