# Generated by Django 5.1.1 on 2024-10-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0028_alter_dependentes_dtexame_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentes',
            name='filiacao',
            field=models.CharField(choices=[('ESPOSA(o)', 'Esposa(o)'), ('FILHO(a)', 'Filho(a)'), ('NETO(a)', 'Neto(a)'), ('BISNETO(a)', 'Bisneto(a)'), ('PAIS', 'Pais')], default='ESPOSA(o)', max_length=50, verbose_name='Filiacao'),
        ),
    ]
