# Generated by Django 4.2.8 on 2024-05-15 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socio', '0028_alter_dependentes_dtexame_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSocio',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=40, null=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('ativo', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='Sim', max_length=10, verbose_name='Ativar Socio')),
                ('tpsocio', models.CharField(choices=[('II', 'Servidor Publico'), ('VI', 'Particular')], default='ESPOSA(o)', max_length=50, verbose_name='Tipo de Socio')),
                ('dtexame_ini', models.DateField(blank=True, null=True, verbose_name='Data do pagamento da taxa da piscina')),
                ('dtexame_fin', models.DateField(blank=True, null=True, verbose_name='Validade da taxa da piscina')),
                ('foto', models.TextField(blank=True, max_length=100, null=True)),
                ('nrcart', models.CharField(max_length=20, null=True)),
                ('registro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero da Matricula no caso de servidor publico')),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='AV/Rua')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Sócio',
                'verbose_name_plural': 'historical Sócios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDependentes',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('filiacao', models.CharField(choices=[('ESPOSA(o)', 'Esposa(o)'), ('FILHO(a)', 'Filho(a)'), ('NETO(a)', 'Neto(a)'), ('BISNETO(a)', 'Bisneto(a)'), ('SOGRO(a)', 'Sogro(a)'), ('PAIS', 'Pais')], default='ESPOSA(o)', max_length=50, verbose_name='Filiacao')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Validade da Filiacao')),
                ('dtexame_ini', models.DateField(blank=True, null=True, verbose_name='Data do pagamento da taxa da piscina')),
                ('dtexame_fin', models.DateField(blank=True, null=True, verbose_name='Validade da taxa da piscina')),
                ('foto', models.TextField(blank=True, max_length=100, null=True)),
                ('nrcart', models.CharField(max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='Sim', max_length=10, verbose_name='Ativar Socio')),
                ('tpsocio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Socio')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('socio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='socio.socio')),
            ],
            options={
                'verbose_name': 'historical Dependente',
                'verbose_name_plural': 'historical Dependentes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
