# Generated by Django 5.1.1 on 2024-11-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0029_alter_dependentes_filiacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentes',
            name='filiacao',
            field=models.CharField(choices=[('ESPOSA(o)', 'Esposa(o)'), ('FILHO(a)', 'Filho(a)'), ('NETO(a)', 'Neto(a)'), ('BISNETO(a)', 'Bisneto(a)'), ('PAI', 'Pai'), ('Mae', 'Mae')], default='ESPOSA(o)', max_length=50, verbose_name='Filiacao'),
        ),
    ]
