# Generated by Django 5.1.1 on 2025-11-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0030_alter_dependentes_filiacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentes',
            name='data_pagamento_ultima_taxa',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do pagamento da última taxa'),
        ),
        migrations.AddField(
            model_name='dependentes',
            name='forma_pagamento_ultima_taxa',
            field=models.CharField(blank=True, choices=[('Cartão', 'Cartão'), ('Dinheiro', 'Dinheiro'), ('Pix', 'Pix')], max_length=20, null=True, verbose_name='Forma de pagamento da última taxa'),
        ),
        migrations.AddField(
            model_name='socio',
            name='data_pagamento_ultima_taxa',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do pagamento da última taxa'),
        ),
        migrations.AddField(
            model_name='socio',
            name='forma_pagamento_ultima_taxa',
            field=models.CharField(blank=True, choices=[('Cartão', 'Cartão'), ('Dinheiro', 'Dinheiro'), ('Pix', 'Pix')], max_length=20, null=True, verbose_name='Forma de pagamento da última taxa'),
        ),
    ]
