# Generated by Django 4.2.8 on 2023-12-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('P', 'Porteiro'), ('S', 'Sócio')], default='S', max_length=1, verbose_name='Tipo de usuário'),
        ),
    ]
